version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=512"
      UV_THREADPOOL_SIZE: 64
      NODE_TLS_REJECT_UNAUTHORIZED: '0'